connectors:
  - connector_id: E2F9AJABjron9RPQdw0K
    service_type: mongodb
    api_key: ''

elasticsearch:
  host: https://localhost:9200
  username: elastic
  password: elastic123
  ca_certs: "/usr/share/elasticsearch/config/certs/ca/ca.crt"
